name: otadex
description: The Ultimate Anime Character Encyclopedia
publish_to: "none"
version: 1.5.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^13.0.0

  # Fonts
  google_fonts: ^6.1.0

  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0

  # Storage local
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0

  # UI & Animations
  smooth_page_indicator: ^1.1.0
  flutter_animate: ^4.3.0
  shimmer: ^3.0.0

  # Assets & Images
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.0

  # Auth & Storage
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0
  google_sign_in: ^6.2.0

  # HTTP client (AniList GraphQL)
  http: ^1.2.0

  # Utils
  gap: ^3.0.1
  url_launcher: ^6.2.0

  # Media
  image_picker: ^1.1.0

  # Notifications
  onesignal_flutter: ^5.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/splash/
    - assets/data/
    - assets/images/Animé pictures/Jujutsu kaizen/Aoi Todo/
    - assets/images/Animé pictures/Jujutsu kaizen/Chojo Kamo/
    - assets/images/Animé pictures/Jujutsu kaizen/Gojo satoru/
    - assets/images/Animé pictures/Jujutsu kaizen/hiromi higumura/
    - assets/images/Animé pictures/Jujutsu kaizen/Kenjaku/
    - assets/images/Animé pictures/Jujutsu kaizen/Mahito/
    - assets/images/Animé pictures/Jujutsu kaizen/Maki Zenin/
    - assets/images/Animé pictures/Jujutsu kaizen/Megumi Fushiguro/
    - assets/images/Animé pictures/Jujutsu kaizen/Nanami Kento/
    - assets/images/Animé pictures/Jujutsu kaizen/Suguru Geto/
    - assets/images/Animé pictures/Jujutsu kaizen/Sukuna/
    - assets/images/Animé pictures/Jujutsu kaizen/Toge Inumaki/
    - assets/images/Animé pictures/Jujutsu kaizen/Toji fushiguro/
    - assets/images/Animé pictures/Jujutsu kaizen/Yuji Itadori/
    - assets/images/Animé pictures/Jujutsu kaizen/Yuta Okkotsu/
    - assets/images/Animé pictures/Naruto Shippuden/Minato Namikaze/
    - assets/images/Animé pictures/Naruto Shippuden/Orochimaru/
    - assets/images/Animé pictures/Naruto Shippuden/Sakura Haruno/
    - assets/images/Animé pictures/Naruto Shippuden/Gaara/
    - assets/images/Animé pictures/Naruto Shippuden/Hashirama Senju/
    - assets/images/Animé pictures/Naruto Shippuden/Hinata Hyuga/
    - assets/images/Animé pictures/Naruto Shippuden/Itachi Uchiha/
    - assets/images/Animé pictures/Naruto Shippuden/Jiraiya/
    - assets/images/Animé pictures/Naruto Shippuden/Kakashi Hatake/
    - assets/images/Animé pictures/Naruto Shippuden/Konan/
    - assets/images/Animé pictures/Naruto Shippuden/Madara Uchiha/
    - assets/images/Animé pictures/Naruto Shippuden/Might Guy/
    - assets/images/Animé pictures/Naruto Shippuden/Naruto Uzumaki/
    - assets/images/Animé pictures/Naruto Shippuden/Neji Hyuga/
    - assets/images/Animé pictures/Naruto Shippuden/Pain/
    - assets/images/Animé pictures/Naruto Shippuden/Rock Lee/
    - assets/images/Animé pictures/Naruto Shippuden/Sasuke Uchiha/
    - assets/images/Animé pictures/Classroom of Elite/Arisu Sakayanagi /
    - assets/images/Animé pictures/Classroom of Elite/honami ichinose/
    - assets/images/Animé pictures/Classroom of Elite/kakeru ryuen/
    - assets/images/Animé pictures/Classroom of Elite/Kei Karuizawa/
    - assets/images/Animé pictures/Classroom of Elite/ken sudo/
    - assets/images/Animé pictures/Classroom of Elite/Kiyotaka Ayanokoji/
    - assets/images/Animé pictures/Classroom of Elite/Manabu Horikita/
    - assets/images/Animé pictures/Classroom of Elite/Suzune Horikita/
    - assets/images/Animé pictures/Classroom of Elite/yosuke hirata/
    - assets/images/Animé pictures/Classroom of Elite/Kikyo Kushida/
    - assets/images/Animé pictures/Classroom of Elite/Sae Chabashira/
    - assets/images/Animé pictures/Classroom of Elite/Rokusuke Koenji/
    - assets/images/Animé pictures/Classroom of Elite/Airi Sakura/
    - assets/images/Animé pictures/Classroom of Elite/Miyabi Nagumo/
    - assets/images/Animé pictures/Classroom of Elite/Hiyori Shiina/
    - assets/images/Animé pictures/Classroom of Elite/Tsubasa Nanase/
    - assets/images/Animé pictures/Classroom of Elite/Ichika Amasawa/
    - assets/images/Animé pictures/Classroom of Elite/Takuya Yagami/
    - assets/images/Animé pictures/Classroom of Elite/Kohei Katsuragi/
    - assets/images/Animé pictures/Classroom of Elite/Mio Ibuki/
    - assets/images/Animé pictures/One piece/Monkey D. Luffy/
    - assets/images/Animé pictures/One piece/Roronoa Zoro/
    - assets/images/Animé pictures/One piece/Sanji Vinsmoke/
    - assets/images/Animé pictures/One piece/Nami/
    - assets/images/Animé pictures/One piece/Trafalgar D. Water Law/
    - assets/images/Animé pictures/One piece/Portgas D. Ace/
    - assets/images/Animé pictures/One piece/Tony Tony Chopper/
    - assets/images/Animé pictures/One piece/Nico Robin/
    - assets/images/Animé pictures/One piece/Boa Hancock/
    - assets/images/Animé pictures/One piece/Shanks le Roux/
    - assets/images/Animé pictures/One piece/Sabo/
    - assets/images/Animé pictures/One piece/Usopp/
    - assets/images/Animé pictures/One piece/Jinbe/
    - assets/images/Animé pictures/One piece/Brook/
    - assets/images/Animé pictures/One piece/Franky/
    - assets/images/Animé pictures/Kuroko no basket/Seijūrō Akashi/
    - assets/images/Animé pictures/Kuroko no basket/Tetsuya Kuroko/
    - assets/images/Animé pictures/Kuroko no basket/Kazunari Takao/
    - assets/images/Animé pictures/Kuroko no basket/Ryōta Kise/
    - assets/images/Animé pictures/Kuroko no basket/Taiga Kagami/
    - assets/images/Animé pictures/Kuroko no basket/Shintarō Midorima/
    - assets/images/Animé pictures/Kuroko no basket/Daiki Aomine/
    - assets/images/Animé pictures/Kuroko no basket/Atsushi Murasakibara/
    - assets/images/Animé pictures/Kuroko no basket/Tatsuya Himuro/
    - assets/images/Animé pictures/Kuroko no basket/Satsuki Momoi/
    - assets/images/Animé pictures/Kuroko no basket/Junpei Hyūga/
    - assets/images/Animé pictures/Kuroko no basket/Teppei Kiyoshi/
    - assets/images/Animé pictures/Kuroko no basket/Riko Aida/
    - assets/images/Animé pictures/Fullmetal Alchemist/Edward Elric/
    - assets/images/Animé pictures/Fullmetal Alchemist/Roy Mustang/
    - assets/images/Animé pictures/Fullmetal Alchemist/Alphonse Elric/
    - assets/images/Animé pictures/Fullmetal Alchemist/Riza Hawkeye/
    - assets/images/Animé pictures/Fullmetal Alchemist/Winry Rockbell/
    - assets/images/Animé pictures/Fullmetal Alchemist/Van Hohenheim/
    - assets/images/Animé pictures/Fullmetal Alchemist/Father/
    - assets/images/Animé pictures/Fullmetal Alchemist/King Bradley/
    - assets/images/Animé pictures/Fullmetal Alchemist/Scar/
    - assets/images/Animé pictures/Fullmetal Alchemist/Maes Hughes/
    - assets/images/Animé pictures/Fullmetal Alchemist/Pride Selim Bradley/
    - assets/images/Animé pictures/Fullmetal Alchemist/Greed Ling Yao/
    - assets/images/Animé pictures/Fullmetal Alchemist/Izumi Curtis/
    - assets/images/Animé pictures/Hunter x Hunter/Killua Zoldyck/
    - assets/images/Animé pictures/Hunter x Hunter/Gon Freecss/
    - assets/images/Animé pictures/Hunter x Hunter/Hisoka Morow/
    - assets/images/Animé pictures/Hunter x Hunter/Kurapika/
    - assets/images/Animé pictures/Hunter x Hunter/Chrollo Lucilfer/
    - assets/images/Animé pictures/Hunter x Hunter/Leorio Paradinight/
    - assets/images/Animé pictures/Hunter x Hunter/Biscuit Krueger/
    - assets/images/Animé pictures/Hunter x Hunter/Meruem/
    - assets/images/Animé pictures/Hunter x Hunter/Isaac Netero/
    - assets/images/Animé pictures/Hunter x Hunter/Illumi Zoldyck/
    - assets/images/Animé pictures/Hunter x Hunter/Ging Freecss/
    - assets/images/Animé pictures/Hunter x Hunter/Feitan Portor/
    - assets/images/Animé pictures/Hunter x Hunter/Neferpitou/
